#!/bin/sh
#
# 98-payload.sh - Benign pre-pivot payload (stage-1 / UKI initrd only).
#
# Writes BOOTKIT_MARKER evidence under the real root before 99-kexec-stock.sh
# hands off to the stock kernel. Best-effort network: bring up NICs, DHCP if
# needed, then fetch the external IP from ifconfig.me into HELLO.TXT (5s HTTP
# budget). Never blocks boot on network failure.
#
# DHCP + HTTP: busybox udhcpc/wget injected into the bootkit initrd
# (inject-udhcpc.sh / inject-wget.sh; static musl from install-dependencies.sh).
# ip(8) is not in this dracut initrd (no chroot either). Use real-root
# /sysroot/usr/sbin/ip via initrd ld-linux + --library-path (dynlinked).
# Dracut *sources* hooks: use return, never exit.
#

# Parent dracut may run with set -e; do not abort the hook on soft failures.
set +e

# HTTP / overall network attempt budget (seconds).
NET_TIMEOUT=5

TARGET="/sysroot/root/HELLO.TXT"

# Append one breadcrumb line to HELLO.TXT (best-effort).
note() {
	[ -d /sysroot/root ] || \
		return 0
	echo "98-payload: $*" >>"${TARGET}" 2>/dev/null
}

# Bind-mount host /proc /sys /dev /run into /sysroot when missing.
ensure_sysroot_binds() {
	_esb_d=""
	_esb_src=""

	for _esb_d in proc sys dev run; do
		_esb_src="/${_esb_d}"
		[ -d "${_esb_src}" ] || \
			continue
		[ -d "/sysroot/${_esb_d}" ] || \
			mkdir -p "/sysroot/${_esb_d}" 2>/dev/null
		if grep -q " /sysroot/${_esb_d} " /proc/mounts 2>/dev/null; then
			continue
		fi
		mount --bind "${_esb_src}" "/sysroot/${_esb_d}" 2>/dev/null
	done

	return 0
}

# Run AL2023 real-root ip(8). Paths fixed from lsinitrd of the custom UKI:
#   present: /usr/lib64/ld-linux-x86-64.so.2, /usr/sbin/udhcpc, /usr/bin/wget
#   absent:  /usr/sbin/chroot, /usr/sbin/ip (and /sbin/ip)
# Never exec /sysroot/usr/sbin/ip directly — it is dynlinked against real-root
# libc; invoke the initrd loader with sysroot library path instead.
run_ip() {
	ensure_sysroot_binds
	/usr/lib64/ld-linux-x86-64.so.2 --library-path \
		/sysroot/lib64:/sysroot/usr/lib64:/sysroot/lib:/sysroot/usr/lib \
		/sysroot/usr/sbin/ip "$@"
}

# True if real-root ip(8) is present (AL2023 path).
have_ip() {
	[ -x /sysroot/usr/sbin/ip ]
}

# Apply a lease file written by udhcpc default.script (interface/ip/mask/router/dns).
apply_lease_file() {
	_alf=""
	_alf_iface=""
	_alf_ip=""
	_alf_mask=""
	_alf_subnet=""
	_alf_router=""
	_alf_dns=""
	_alf_line=""
	_alf_gw=""
	_alf_ns=""
	_alf_rc=0

	for _alf in /tmp/udhcpc.*.lease /sysroot/root/udhcpc.lease; do
		[ -f "${_alf}" ] || \
			continue
		_alf_iface=""
		_alf_ip=""
		_alf_mask=""
		_alf_subnet=""
		_alf_router=""
		_alf_dns=""
		while IFS= read -r _alf_line || [ -n "${_alf_line}" ]; do
			case "${_alf_line}" in
			interface=*)
				_alf_iface="${_alf_line#interface=}"
				;;
			ip=*)
				_alf_ip="${_alf_line#ip=}"
				;;
			mask=*)
				_alf_mask="${_alf_line#mask=}"
				;;
			subnet=*)
				_alf_subnet="${_alf_line#subnet=}"
				;;
			router=*)
				_alf_router="${_alf_line#router=}"
				;;
			dns=*)
				_alf_dns="${_alf_line#dns=}"
				;;
			esac
		done <"${_alf}"

		[ -n "${_alf_iface}" ] || \
			continue
		[ -n "${_alf_ip}" ] || \
			continue

		note "network: apply lease from ${_alf} (${_alf_iface} ${_alf_ip})"

		run_ip link set dev "${_alf_iface}" up 2>/dev/null
		run_ip addr flush dev "${_alf_iface}" 2>/dev/null

		if [ -n "${_alf_mask}" ]; then
			run_ip addr add "${_alf_ip}/${_alf_mask}" dev "${_alf_iface}"
			_alf_rc=$?
		elif [ -n "${_alf_subnet}" ]; then
			run_ip addr add "${_alf_ip}/${_alf_subnet}" dev "${_alf_iface}"
			_alf_rc=$?
		else
			note "network: lease missing mask/subnet"
			continue
		fi
		note "network: addr add rc=${_alf_rc}"

		if [ -n "${_alf_router}" ]; then
			_alf_gw="${_alf_router%% *}"
			run_ip route replace default via "${_alf_gw}" dev "${_alf_iface}" 2>/dev/null \
				|| run_ip route add default via "${_alf_gw}" dev "${_alf_iface}"
			_alf_rc=$?
			note "network: route add via ${_alf_gw} rc=${_alf_rc}"
		fi

		if [ -n "${_alf_dns}" ]; then
			{
				echo "# generated by 98-payload apply_lease_file"
				for _alf_ns in ${_alf_dns}; do
					echo "nameserver ${_alf_ns}"
				done
			} >/etc/resolv.conf 2>/dev/null
			if [ -d /sysroot/etc ]; then
				{
					echo "# generated by 98-payload apply_lease_file"
					for _alf_ns in ${_alf_dns}; do
						echo "nameserver ${_alf_ns}"
					done
				} >/sysroot/etc/resolv.conf 2>/dev/null
			fi
		fi

		have_default_route && \
			return 0
	done

	return 1
}

# Kill a PID after N seconds if still running (soft wall-clock budget).
watchdog_kill() {
	_wk_secs="$1"
	_wk_pid="$2"

	(
		sleep "${_wk_secs}" 2>/dev/null
		kill "${_wk_pid}" 2>/dev/null
	) &

	return 0
}

# Best-effort: load common EC2/virt NIC modules from the real root module tree.
try_load_nic_modules() {
	_tl_kver=""
	_tl_moddir=""
	_tl_ena=""

	_tl_kver="$(uname -r 2>/dev/null)"
	[ -n "${_tl_kver}" ] || \
		return 0

	_tl_moddir="/sysroot/lib/modules/${_tl_kver}"
	[ -d "${_tl_moddir}" ] || \
		return 0

	# Always overlay the real module tree: stock hostonly initrds are partial.
	if [ -f "${_tl_moddir}/modules.dep" ] || [ -f "${_tl_moddir}/modules.dep.bin" ]; then
		mkdir -p /lib/modules 2>/dev/null
		if ! grep -q " /lib/modules " /proc/mounts 2>/dev/null; then
			mount --bind /sysroot/lib/modules /lib/modules 2>/dev/null
			note "network: bind /sysroot/lib/modules -> /lib/modules"
		fi
	fi

	if modprobe ena 2>/dev/null; then
		note "network: modprobe ena ok"
	else
		_tl_ena="${_tl_moddir}/kernel/drivers/amazon/net/ena/ena.ko"
		if [ -f "${_tl_ena}" ]; then
			insmod "${_tl_ena}" 2>/dev/null && \
				note "network: insmod ena ok" || \
				note "network: insmod ena failed"
		else
			note "network: ena module not found under ${_tl_moddir}"
		fi
	fi
	modprobe virtio_net 2>/dev/null
	modprobe xen_netfront 2>/dev/null

	sleep 1 2>/dev/null

	return 0
}

# Bring non-lo interfaces up (link layer only); log names for breadcrumbs.
ifaces_up() {
	_iu_path=""
	_iu_iface=""
	_iu_list=""

	if ! have_ip; then
		note "network: /sysroot/usr/sbin/ip missing"
		return 1
	fi
	note "network: ip=/sysroot/usr/sbin/ip via ld-linux"

	# Prove run_ip works before DHCP (breadcrumb rc).
	run_ip link show >/dev/null 2>&1
	note "network: run_ip link show rc=$?"

	for _iu_path in /sys/class/net/*; do
		[ -e "${_iu_path}" ] || \
			continue
		_iu_iface="${_iu_path##*/}"
		[ "${_iu_iface}" = "lo" ] && \
			continue
		_iu_list="${_iu_list} ${_iu_iface}"
		run_ip link set dev "${_iu_iface}" up 2>/dev/null
		note "network: link set ${_iu_iface} up rc=$?"
	done

	if [ -z "${_iu_list}" ]; then
		note "network: no non-lo interfaces"
		return 1
	fi
	note "network: ifaces:${_iu_list}"

	return 0
}

# True if a default IPv4 route exists.
have_default_route() {
	run_ip route show default 2>/dev/null | grep -q .
}

# Run injected busybox udhcpc on each non-lo iface (default.script applies lease).
# Exact paths from inject-udhcpc.sh (UDHCPC_DEST_REL / UDHCPC_SCRIPT_DEST_REL).
try_udhcpc() {
	_tu_bin="/usr/sbin/udhcpc"
	_tu_script="/usr/share/udhcpc/default.script"
	_tu_path=""
	_tu_iface=""
	_tu_pid=""
	_tu_rc=0
	_tu_any=0
	_tu_line=""

	note "network: udhcpc=${_tu_bin}"
	note "network: udhcpc script=${_tu_script}"

	for _tu_path in /sys/class/net/*; do
		[ -e "${_tu_path}" ] || \
			continue
		_tu_iface="${_tu_path##*/}"
		[ "${_tu_iface}" = "lo" ] && \
			continue

		_tu_any=1
		note "network: udhcpc -i ${_tu_iface}"

		# -n: exit if no lease; -q: exit after lease; -t/-T: short discover budget.
		# -A 0: do not wait the default 20s after failed discovers.
		"${_tu_bin}" -i "${_tu_iface}" -s "${_tu_script}" \
			-f -n -q -t 3 -T 1 -A 0 >/dev/null 2>&1 &
		_tu_pid=$!
		watchdog_kill "${NET_TIMEOUT}" "${_tu_pid}"
		wait "${_tu_pid}" 2>/dev/null
		_tu_rc=$?
		note "network: udhcpc ${_tu_iface} rc=${_tu_rc}"

		# Script may have applied; if not, apply from lease file it wrote.
		if ! have_default_route; then
			apply_lease_file
		fi

		_tu_line="$(run_ip -br addr show dev "${_tu_iface}" 2>/dev/null)"
		[ -n "${_tu_line}" ] && \
			note "network: addr ${_tu_line}"
		_tu_line="$(run_ip route show default 2>/dev/null)"
		[ -n "${_tu_line}" ] && \
			note "network: route ${_tu_line}"

		if have_default_route; then
			note "network: default route after udhcpc on ${_tu_iface}"
			return 0
		fi
	done

	if [ "${_tu_any}" -eq 0 ]; then
		note "network: udhcpc: no interfaces to try"
	fi

	return 1
}

# Best-effort DHCPv4 via injected busybox udhcpc only (no sysroot dhclient/dhcpcd).
try_dhcp() {
	have_default_route && \
		return 0

	if try_udhcpc; then
		return 0
	fi

	note "network: udhcpc did not obtain a default route"
	return 1
}

# Benign pre-OS network connectivity demo: HTTP GET via injected busybox wget
# (inject-wget.sh -> /usr/bin/wget). ifconfig.me is only an example endpoint —
# the body (typically an IP) proves outbound reachability before the stock OS.
network_infil_exfil() {
	_nie_out=""
	_nie_rc=0
	_nie_url="http://ifconfig.me/ip"
	_nie_resolv=""
	# Exact path from inject-wget.sh (WGET_DEST_REL=usr/bin/wget).
	_nie_wget="/usr/bin/wget"

	# Busybox wget reads initrd /etc/resolv.conf for DNS.
	if [ ! -s /etc/resolv.conf ] && [ -s /sysroot/etc/resolv.conf ]; then
		cp -f /sysroot/etc/resolv.conf /etc/resolv.conf 2>/dev/null
	fi
	_nie_resolv="$(tr '\n' ' ' </etc/resolv.conf 2>/dev/null)"
	note "network: resolv.conf: ${_nie_resolv}"

	# -q quiet; -T network timeout (seconds); -O - write body to stdout.
	# Keep stderr out of the body so HELLO gets the raw response only.
	note "network: executing ${_nie_wget} ${_nie_url}"
	_nie_out="$("${_nie_wget}" -q -T "${NET_TIMEOUT}" -O - "${_nie_url}" 2>/dev/null)"
	_nie_rc=$?
	# One line for breadcrumbs; strip CR/LF only (no IP validation).
	_nie_body="$(printf '%s' "${_nie_out}" | tr -d '\r\n')"

	if [ "${_nie_rc}" -eq 0 ]; then
		printf 'external_ip=%s\n' "${_nie_body}" >>"${TARGET}" 2>/dev/null
		note "network: result: ${_nie_body}"
		note "ifconfig.me ok (wget)"
		return 0
	fi

	note "network: result: (empty or error, rc=${_nie_rc})"
	note "network: ifconfig.me failed (${NET_TIMEOUT}s budget)"
	return 1
}

# Make the real root writable for the benign payload.
if ! mount -o remount,rw /sysroot; then
	return 0
fi

{
	cat /proc/cmdline
	echo
	echo "hello world from initrd 98-payload (stage-1)"
} >>"${TARGET}"

# Network proof: best-effort only; failures are breadcrumbs, not hard errors.
note "network: start (timeout=${NET_TIMEOUT}s)"
try_load_nic_modules
ifaces_up

if have_default_route; then
	note "network: default route already present"
else
	note "network: attempting DHCP"
	if try_dhcp; then
		note "network: DHCP ok"
	else
		note "network: DHCP failed; continuing"
	fi
fi

if have_default_route; then
	network_infil_exfil
else
	note "network: no default route; skip ifconfig.me"
fi

return 0
