#!/usr/bin/env bash
#
# append-deploy-trailer.sh - Append BOOTX64.EFI + uki.efi trailer to ELF.
#
# Usage:
#   append-deploy-trailer.sh <bare-elf> <BOOTX64.EFI> <uki.efi> <out>
#
# Reads 16-byte magic from deploy-magic.h in the current directory
# (generated by gen-deploy-magic.sh). Layout:
#   [ELF][MAGIC][u64 le size][BOOTX64][MAGIC][u64 le size][uki]
#
set -euo pipefail
IFS=$'\n\t'

readonly __script_path="${BASH_SOURCE[0]}"
# shellcheck disable=SC2155
readonly __progname="$(basename "${__script_path}")"
readonly PATH="/usr/sbin:/usr/bin:/sbin:/bin"

readonly MAGIC_H="deploy-magic.h"
readonly MAGIC_LEN=16

errx() {
	echo -e "${__progname}: $*" >&2

	exit 1
}

usage() {
	echo -e "usage: ${__progname} <bare-elf> <BOOTX64.EFI> <uki.efi> <out>" >&2

	exit 1
}

# Extract 16 raw magic bytes from deploy-magic.h into path.
magic_from_header() {
	local -r dest="${1}"
	local -r hdr="${2}"
	local hex=""

	[ -f "${hdr}" ] || \
		errx "missing ${hdr} (run gen-deploy-magic.sh first)"

	# Collect 0xNN tokens from the array body.
	hex="$(
		# shellcheck disable=SC2016
		awk '
			/deploy_magic\[/ { inarr=1; next }
			inarr && /};/ { exit }
			inarr {
				gsub(/0x/, "")
				gsub(/,/, " ")
				gsub(/[^0-9a-fA-F \t]/, "")
				printf "%s", $0
			}
		' "${hdr}" | tr -d ' \t\n'
	)"
	[ "${#hex}" -eq $((MAGIC_LEN * 2)) ] || \
		errx "could not parse ${MAGIC_LEN} magic bytes from ${hdr}"

	printf '%s' "${hex}" | xxd -r -p >"${dest}"
	[ "$(stat -c '%s' -- "${dest}" 2>/dev/null || stat -f '%z' -- "${dest}")" -eq "${MAGIC_LEN}" ] || \
		errx "magic file size is not ${MAGIC_LEN}"
}

# Write little-endian u64 size to stdout as raw bytes.
write_u64_le() {
	local -r n="${1}"
	local hex=""
	local i=0
	local b=0

	hex=""
	for ((i = 0; i < 8; i++)); do
		b=$(( (n >> (8 * i)) & 0xff ))
		printf -v hex '%s%02x' "${hex}" "${b}"
	done
	printf '%s' "${hex}" | xxd -r -p
}

main() {
	[[ "$#" -ne 4 ]] && \
		usage

	for bin in awk tr xxd stat cat cp; do
		! command -v "${bin}" >/dev/null 2>&1 && \
			errx "cannot find '${bin}' in 'PATH=${PATH}'"
	done

	local -r bare="${1}"
	local -r bootx64="${2}"
	local -r uki="${3}"
	local -r out="${4}"
	local boot_sz=0
	local uki_sz=0
	local magic_bin=""
	# Global so the EXIT trap can see it after main returns (set -u).
	_append_tmpdir=""

	[ -f "${bare}" ] || \
		errx "missing bare ELF: ${bare}"
	[ -f "${bootx64}" ] || \
		errx "missing BOOTX64.EFI: ${bootx64}"
	[ -f "${uki}" ] || \
		errx "missing uki.efi: ${uki}"

	boot_sz="$(stat -c '%s' -- "${bootx64}" 2>/dev/null || stat -f '%z' -- "${bootx64}")"
	uki_sz="$(stat -c '%s' -- "${uki}" 2>/dev/null || stat -f '%z' -- "${uki}")"
	[ "${boot_sz}" -gt 0 ] || \
		errx "BOOTX64.EFI is empty"
	[ "${uki_sz}" -gt 0 ] || \
		errx "uki.efi is empty"

	trap '[ -n "${_append_tmpdir:-}" ] && rm -rf -- "${_append_tmpdir}"' EXIT
	_append_tmpdir="$(mktemp -d "/tmp/${__progname}.XXXXXX")"
	[ -d "${_append_tmpdir}" ] || \
		errx "mktemp -d"

	magic_bin="${_append_tmpdir}/magic.bin"
	magic_from_header "${magic_bin}" "${MAGIC_H}"

	cp -f -- "${bare}" "${out}.tmp"
	{
		cat -- "${magic_bin}"
		write_u64_le "${boot_sz}"
		cat -- "${bootx64}"
		cat -- "${magic_bin}"
		write_u64_le "${uki_sz}"
		cat -- "${uki}"
	} >>"${out}.tmp"
	mv -f -- "${out}.tmp" "${out}"
	chmod 0755 "${out}"

	echo "${__progname}: ${out} (BOOTX64=${boot_sz} uki=${uki_sz} magic=${MAGIC_LEN})"
}

main "$@"
