#!/usr/bin/env bash
#
# gen-deploy-magic.sh - Emit deploy-magic.h from SOURCE_DATE_EPOCH.
#
# Writes a 16-byte magic array: first 16 bytes of
# SHA-256("grub2-bootkit-deploy-v1\0" || SOURCE_DATE_EPOCH).
# Usage: gen-deploy-magic.sh <output.h>
# Env: SOURCE_DATE_EPOCH (default 0).
#
set -euo pipefail
IFS=$'\n\t'

readonly __script_path="${BASH_SOURCE[0]}"
# shellcheck disable=SC2155
readonly __progname="$(basename "${__script_path}")"
readonly PATH="/usr/sbin:/usr/bin:/sbin:/bin"

readonly DOMAIN="grub2-bootkit-deploy-v1"
readonly MAGIC_LEN=16

errx() {
	echo -e "${__progname}: $*" >&2

	exit 1
}

usage() {
	echo -e "usage: ${__progname} <output.h>" >&2

	exit 1
}

# Write C header with deploy_magic[16] to path.
write_header() {
	local -r out="${1}"
	local -r epoch="${2}"
	local hex=""
	local i=0
	local b=""
	local -a bytes=()
	local line=""

	# First 16 bytes of SHA-256(domain || NUL || epoch ascii).
	hex="$(printf '%s\0%s' "${DOMAIN}" "${epoch}" | openssl dgst -sha256 -binary | \
		od -An -tx1 -N "${MAGIC_LEN}" | tr -d ' \n')"
	[ "${#hex}" -eq $((MAGIC_LEN * 2)) ] || \
		errx "unexpected hash length from openssl/od"

	bytes=()
	for ((i = 0; i < MAGIC_LEN; i++)); do
		b="${hex:$((i * 2)):2}"
		bytes+=("0x${b}")
	done

	line="$(IFS=', '; echo "${bytes[*]}")"

	{
		echo "/*"
		echo " * Generated by ${__progname} — do not edit."
		echo " * SOURCE_DATE_EPOCH=${epoch}"
		echo " */"
		echo "#ifndef DEPLOY_MAGIC_H"
		echo "#define DEPLOY_MAGIC_H"
		echo ""
		echo "#include <stdint.h>"
		echo ""
		echo "static const uint8_t deploy_magic[${MAGIC_LEN}] = {"
		echo "	${line}"
		echo "};"
		echo ""
		echo "#endif /* DEPLOY_MAGIC_H */"
	} >"${out}"
}

main() {
	[[ "$#" -ne 1 ]] && \
		usage

	for bin in openssl od tr; do
		! command -v "${bin}" >/dev/null 2>&1 && \
			errx "cannot find '${bin}' in 'PATH=${PATH}'"
	done

	local -r out="${1}"
	local -r epoch="${SOURCE_DATE_EPOCH:-0}"

	write_header "${out}" "${epoch}"
	echo "${__progname}: wrote ${out} (SOURCE_DATE_EPOCH=${epoch})"
}

main "$@"
