#!/usr/bin/env bash
#
# inject-udhcpc.sh - Copy pinned busybox udhcpc (+ default.script) into an initrd main/ tree.
#
# Usage: inject-udhcpc.sh <path-to-main>
# Expects busybox_UDHCPC beside this script (fetched by install-dependencies.sh:
# static musl busybox 1.35.0 UDHCPC applet). No shared libs required.
#
set -euo pipefail
IFS=$'\n\t'

readonly __script_path="${BASH_SOURCE[0]}"
# shellcheck disable=SC2155
readonly __progname="$(basename "${__script_path}")"
readonly PATH="/usr/sbin:/usr/bin:/sbin:/bin"

# Host-side binary name (install-dependencies.sh version pin + sha256).
readonly UDHCPC_HOST_NAME="busybox_UDHCPC"
# Paths inside the initrd main/ tree (payload looks here first).
readonly UDHCPC_DEST_REL="usr/sbin/udhcpc"
readonly UDHCPC_SCRIPT_DEST_REL="usr/share/udhcpc/default.script"

errx() {
	echo -e "${__progname}: $*" >&2

	exit 1
}

usage() {
	echo -e "usage: ${__progname} <path-to-main>" >&2

	exit 1
}

# Event script: record lease for 98-payload; best-effort apply via chroot/ld.so ip.
write_default_script() {
	local -r dest="${1}"
	local dest_dir=""

	dest_dir="$(dirname -- "${dest}")"
	mkdir -p -- "${dest_dir}"

	# Lease file is the source of truth for 98-payload.sh (applies with run_ip).
	# This script also tries to apply immediately so a working ip path is enough.
	# shellcheck disable=SC2016
	cat >"${dest}" <<'EOF'
#!/bin/sh
# udhcpc default.script - record + apply DHCPv4 lease (busybox udhcpc events).
# inject-udhcpc.sh installs this into the bootkit initrd.
# PATH is often minimal when udhcpc invokes us; use absolute paths only.

PATH="/usr/sbin:/usr/bin:/sbin:/bin"
export PATH

[ -z "${interface}" ] && \
	exit 0

LEASE_FILE="/tmp/udhcpc.${interface}.lease"
LEASE_COPY="/sysroot/root/udhcpc.lease"
HELLO="/sysroot/root/HELLO.TXT"

# Best-effort breadcrumb into HELLO.TXT (same file as 98-payload).
slog() {
	[ -d /sysroot/root ] || \
		return 0
	echo "udhcpc-script: $*" >>"${HELLO}" 2>/dev/null
}

# Persist lease env for 98-payload to apply if we cannot run ip here.
write_lease_file() {
	{
		echo "interface=${interface}"
		echo "ip=${ip:-}"
		echo "mask=${mask:-}"
		echo "subnet=${subnet:-}"
		echo "router=${router:-}"
		echo "dns=${dns:-}"
		echo "event=${1:-}"
	} >"${LEASE_FILE}" 2>/dev/null
	if [ -d /sysroot/root ]; then
		cp -f "${LEASE_FILE}" "${LEASE_COPY}" 2>/dev/null \
			|| cat "${LEASE_FILE}" >"${LEASE_COPY}" 2>/dev/null
	fi
	return 0
}

# AL2023: initrd has no chroot/ip; has /usr/lib64/ld-linux-x86-64.so.2.
# Real-root iproute is /sysroot/usr/sbin/ip (dynlinked) — run via loader.
run_ip() {
	/usr/lib64/ld-linux-x86-64.so.2 --library-path \
		/sysroot/lib64:/sysroot/usr/lib64:/sysroot/lib:/sysroot/usr/lib \
		/sysroot/usr/sbin/ip "$@"
}

write_resolv() {
	_wr_ns=""
	[ -n "${dns}" ] || \
		return 0
	{
		echo "# generated by udhcpc default.script"
		for _wr_ns in ${dns}; do
			echo "nameserver ${_wr_ns}"
		done
	} >/etc/resolv.conf 2>/dev/null
	if [ -d /sysroot/etc ]; then
		{
			echo "# generated by udhcpc default.script"
			for _wr_ns in ${dns}; do
				echo "nameserver ${_wr_ns}"
			done
		} >/sysroot/etc/resolv.conf 2>/dev/null
	fi
	return 0
}

# Apply address + default route from current udhcpc environment.
apply_lease() {
	_al_gw=""
	_al_rc=0

	run_ip link set dev "${interface}" up
	_al_rc=$?
	slog "link up rc=${_al_rc}"

	run_ip addr flush dev "${interface}" 2>/dev/null

	if [ -n "${ip}" ] && [ -n "${mask}" ]; then
		run_ip addr add "${ip}/${mask}" dev "${interface}"
		_al_rc=$?
		slog "addr add ${ip}/${mask} rc=${_al_rc}"
	elif [ -n "${ip}" ] && [ -n "${subnet}" ]; then
		run_ip addr add "${ip}/${subnet}" dev "${interface}"
		_al_rc=$?
		slog "addr add ${ip}/${subnet} rc=${_al_rc}"
	else
		slog "addr add skipped (ip='${ip}' mask='${mask}' subnet='${subnet}')"
	fi

	if [ -n "${router}" ]; then
		_al_gw="${router%% *}"
		run_ip route replace default via "${_al_gw}" dev "${interface}" 2>/dev/null \
			|| run_ip route add default via "${_al_gw}" dev "${interface}"
		_al_rc=$?
		slog "route default via ${_al_gw} rc=${_al_rc}"
	else
		slog "route skipped (no router)"
	fi

	write_resolv
	return 0
}

case "${1}" in
deconfig)
	write_lease_file deconfig
	run_ip addr flush dev "${interface}" 2>/dev/null
	run_ip link set dev "${interface}" up 2>/dev/null
	slog "deconfig ${interface}"
	;;
bound|renew)
	write_lease_file "${1}"
	slog "bound ${interface} ip=${ip} mask=${mask} router=${router} dns=${dns}"
	apply_lease
	;;
leasefail|nak)
	write_lease_file "${1}"
	slog "${1} ${interface}"
	;;
esac

exit 0
EOF

	chmod 0755 -- "${dest}"

	return 0
}

main() {
	[[ "$#" -ne 1 ]] && \
		usage

	for bin in cp mkdir dirname chmod cat; do
		! command -v "${bin}" >/dev/null 2>&1 && \
			errx "cannot find '${bin}' in 'PATH=${PATH}'"
	done

	local -r tree="${1}"
	local -r repo_root="$(cd "$(dirname "${__script_path}")" && pwd)"
	local -r host_bin="${repo_root}/${UDHCPC_HOST_NAME}"
	local -r dest_bin="${tree}/${UDHCPC_DEST_REL}"
	local -r dest_script="${tree}/${UDHCPC_SCRIPT_DEST_REL}"
	local dest_dir=""

	[ ! -d "${tree}" ] && \
		errx "main tree not found: ${tree}"

	[ ! -f "${host_bin}" ] && \
		errx "missing ${host_bin} (run ./install-dependencies.sh)"
	[ ! -s "${host_bin}" ] && \
		errx "empty binary: ${host_bin}"

	dest_dir="$(dirname -- "${dest_bin}")"
	mkdir -p -- "${dest_dir}"
	cp -f -- "${host_bin}" "${dest_bin}"
	chmod 0755 -- "${dest_bin}"

	write_default_script "${dest_script}"

	echo "${__progname}: installed ${dest_bin} (from ${host_bin})"
	echo "${__progname}: installed ${dest_script}"
}

main "$@"
